### PR TITLE
File and DIR API

### PR DESCRIPTION
**Pull request by Antidote**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/Antidote/Athena/pull/10%23issuecomment-103211422%22%2C%20%22https%3A//github.com/Antidote/Athena/pull/10%23issuecomment-103321523%22%2C%20%22https%3A//github.com/Antidote/Athena/pull/10%23issuecomment-104138349%22%2C%20%22https%3A//github.com/Antidote/Athena/pull/10%23issuecomment-104139072%22%2C%20%22https%3A//github.com/Antidote/Athena/pull/10%23issuecomment-104147573%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/Antidote/Athena/pull/10%23issuecomment-103211422%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Dir%20needs%20to%20be%20finished%2C%20and%20I%27m%20not%20sure%20about%20FileInfo%20quite%20yet.%20The%20touch%20implementation%20is%20still%20iffy.%20%3A8ball%3A%20%22%2C%20%22created_at%22%3A%20%222015-05-18T21%3A08%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3392773%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Antidote%22%7D%7D%2C%20%7B%22body%22%3A%20%22Fixed%20merge%20%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-05-19T03%3A38%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3392773%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Antidote%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-05-21T05%3A13%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/505536%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jackoalan%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%3Agun%3A%22%2C%20%22created_at%22%3A%20%222015-05-21T05%3A15%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/505536%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jackoalan%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-05-21T05%3A53%3A57Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/505536%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jackoalan%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/jackoalan%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/505536%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/jackoalan'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/Antidote/Athena/pull/10#issuecomment-103211422'>General Comment</a></b>
- <a href='https://github.com/Antidote'></a> Dir needs to be finished, and I'm not sure about FileInfo quite yet. The touch implementation is still iffy. :8ball:
- <a href='https://github.com/Antidote'></a> Fixed merge :+1:
- <a href='https://github.com/jackoalan'></a> :shipit:
- <a href='https://github.com/jackoalan'></a> :shipit::gun:

<a href='https://www.codereviewhub.com/Antidote/Athena/pull/10?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/Antidote/Athena/pull/10?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/Antidote/Athena/pull/10?approve=0'></a>&nbsp;<a href='https://github.com/Antidote/Athena/pull/10'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by Antidote** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/Antidote/Athena/pull/10'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Antidote** [comment]
Dir needs to be finished, and I'm not sure about FileInfo quite yet. The touch implementation is still iffy.

**Comment by jackoalan** [comment]
:shipit:

**Comment by Antidote** [comment]
:shipit::gun:

**Comment by Antidote** [comment]
:shipit::gun:

**Comment by Antidote** [comment]
:shipit::gun:

**Comment by Antidote** [comment]
Fixed merge :+1:

**Comment by jackoalan** [comment]
:shipit:

**Comment by jackoalan** [comment]
:shipit::gun:

**Comment by jackoalan** [comment]
:shipit:

**Pull request merged**
