### PR TITLE
Reimplement exception handling

### PR DESCRIPTION
**Pull request by Antidote**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/Antidote/Athena/pull/11%23issuecomment-103262396%22%2C%20%22https%3A//github.com/Antidote/Athena/pull/11%23issuecomment-103266143%22%2C%20%22https%3A//github.com/Antidote/Athena/pull/11%23issuecomment-103266533%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/Antidote/Athena/pull/11%23issuecomment-103262396%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Stage%201%20%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-05-18T23%3A30%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3392773%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Antidote%22%7D%7D%2C%20%7B%22body%22%3A%20%22Stage%202%20%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-05-18T23%3A39%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3392773%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Antidote%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-05-18T23%3A41%3A19Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/505536%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jackoalan%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/jackoalan%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/505536%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/jackoalan'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/Antidote/Athena/pull/11#issuecomment-103262396'>General Comment</a></b>
- <a href='https://github.com/Antidote'></a> Stage 1 :+1:
- <a href='https://github.com/Antidote'></a> Stage 2 :+1:

<a href='https://www.codereviewhub.com/Antidote/Athena/pull/11?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/Antidote/Athena/pull/11?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/Antidote/Athena/pull/11?approve=0'></a>&nbsp;<a href='https://github.com/Antidote/Athena/pull/11'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by Antidote** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/Antidote/Athena/pull/11'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Antidote** [comment]
Stage one :+1:

**Comment by Antidote** [comment]
Stage 2 :-1:

**Comment by Antidote** [comment]
Stage 2 :+1:

**Comment by jackoalan** [comment]
:shipit:

**Pull request merged**
